// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hackathonaccountrecovery/hackathonaccountrecovery/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryShowAccountRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryShowAccountRequest) Reset()         { *m = QueryShowAccountRequest{} }
func (m *QueryShowAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowAccountRequest) ProtoMessage()    {}
func (*QueryShowAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{2}
}
func (m *QueryShowAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowAccountRequest.Merge(m, src)
}
func (m *QueryShowAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowAccountRequest proto.InternalMessageInfo

func (m *QueryShowAccountRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type QueryShowAccountResponse struct {
	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *QueryShowAccountResponse) Reset()         { *m = QueryShowAccountResponse{} }
func (m *QueryShowAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowAccountResponse) ProtoMessage()    {}
func (*QueryShowAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{3}
}
func (m *QueryShowAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowAccountResponse.Merge(m, src)
}
func (m *QueryShowAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowAccountResponse proto.InternalMessageInfo

func (m *QueryShowAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type QueryListAccountRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListAccountRequest) Reset()         { *m = QueryListAccountRequest{} }
func (m *QueryListAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListAccountRequest) ProtoMessage()    {}
func (*QueryListAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{4}
}
func (m *QueryListAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListAccountRequest.Merge(m, src)
}
func (m *QueryListAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListAccountRequest proto.InternalMessageInfo

func (m *QueryListAccountRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListAccountResponse struct {
	Account    []Account           `protobuf:"bytes,1,rep,name=account,proto3" json:"account"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListAccountResponse) Reset()         { *m = QueryListAccountResponse{} }
func (m *QueryListAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListAccountResponse) ProtoMessage()    {}
func (*QueryListAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{5}
}
func (m *QueryListAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListAccountResponse.Merge(m, src)
}
func (m *QueryListAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListAccountResponse proto.InternalMessageInfo

func (m *QueryListAccountResponse) GetAccount() []Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *QueryListAccountResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetShareKeysRequest struct {
	Key         string             `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Totalshares int64              `protobuf:"varint,2,opt,name=totalshares,proto3" json:"totalshares,omitempty"`
	Minshares   int64              `protobuf:"varint,3,opt,name=minshares,proto3" json:"minshares,omitempty"`
	Pagination  *query.PageRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetShareKeysRequest) Reset()         { *m = QueryGetShareKeysRequest{} }
func (m *QueryGetShareKeysRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetShareKeysRequest) ProtoMessage()    {}
func (*QueryGetShareKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{6}
}
func (m *QueryGetShareKeysRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetShareKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetShareKeysRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetShareKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetShareKeysRequest.Merge(m, src)
}
func (m *QueryGetShareKeysRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetShareKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetShareKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetShareKeysRequest proto.InternalMessageInfo

func (m *QueryGetShareKeysRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *QueryGetShareKeysRequest) GetTotalshares() int64 {
	if m != nil {
		return m.Totalshares
	}
	return 0
}

func (m *QueryGetShareKeysRequest) GetMinshares() int64 {
	if m != nil {
		return m.Minshares
	}
	return 0
}

func (m *QueryGetShareKeysRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetShareKeysResponse struct {
	Secretkey []string `protobuf:"bytes,1,rep,name=secretkey,proto3" json:"secretkey,omitempty"`
}

func (m *QueryGetShareKeysResponse) Reset()         { *m = QueryGetShareKeysResponse{} }
func (m *QueryGetShareKeysResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetShareKeysResponse) ProtoMessage()    {}
func (*QueryGetShareKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{7}
}
func (m *QueryGetShareKeysResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetShareKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetShareKeysResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetShareKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetShareKeysResponse.Merge(m, src)
}
func (m *QueryGetShareKeysResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetShareKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetShareKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetShareKeysResponse proto.InternalMessageInfo

func (m *QueryGetShareKeysResponse) GetSecretkey() []string {
	if m != nil {
		return m.Secretkey
	}
	return nil
}

type QueryGetSecretKeyRequest struct {
	AccountOwner string `protobuf:"bytes,1,opt,name=accountOwner,proto3" json:"accountOwner,omitempty"`
}

func (m *QueryGetSecretKeyRequest) Reset()         { *m = QueryGetSecretKeyRequest{} }
func (m *QueryGetSecretKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSecretKeyRequest) ProtoMessage()    {}
func (*QueryGetSecretKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{8}
}
func (m *QueryGetSecretKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSecretKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSecretKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSecretKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSecretKeyRequest.Merge(m, src)
}
func (m *QueryGetSecretKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSecretKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSecretKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSecretKeyRequest proto.InternalMessageInfo

func (m *QueryGetSecretKeyRequest) GetAccountOwner() string {
	if m != nil {
		return m.AccountOwner
	}
	return ""
}

type QueryGetSecretKeyResponse struct {
	SecretKey string `protobuf:"bytes,1,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
}

func (m *QueryGetSecretKeyResponse) Reset()         { *m = QueryGetSecretKeyResponse{} }
func (m *QueryGetSecretKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSecretKeyResponse) ProtoMessage()    {}
func (*QueryGetSecretKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{9}
}
func (m *QueryGetSecretKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSecretKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSecretKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSecretKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSecretKeyResponse.Merge(m, src)
}
func (m *QueryGetSecretKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSecretKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSecretKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSecretKeyResponse proto.InternalMessageInfo

func (m *QueryGetSecretKeyResponse) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type QueryGetMappedAccountsRequest struct {
	Account    string             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetMappedAccountsRequest) Reset()         { *m = QueryGetMappedAccountsRequest{} }
func (m *QueryGetMappedAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMappedAccountsRequest) ProtoMessage()    {}
func (*QueryGetMappedAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{10}
}
func (m *QueryGetMappedAccountsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMappedAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMappedAccountsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMappedAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMappedAccountsRequest.Merge(m, src)
}
func (m *QueryGetMappedAccountsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMappedAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMappedAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMappedAccountsRequest proto.InternalMessageInfo

func (m *QueryGetMappedAccountsRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *QueryGetMappedAccountsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetMappedAccountsResponse struct {
	Account    []Account           `protobuf:"bytes,1,rep,name=account,proto3" json:"account"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetMappedAccountsResponse) Reset()         { *m = QueryGetMappedAccountsResponse{} }
func (m *QueryGetMappedAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMappedAccountsResponse) ProtoMessage()    {}
func (*QueryGetMappedAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3366ed22c2ad7f0, []int{11}
}
func (m *QueryGetMappedAccountsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMappedAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMappedAccountsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMappedAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMappedAccountsResponse.Merge(m, src)
}
func (m *QueryGetMappedAccountsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMappedAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMappedAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMappedAccountsResponse proto.InternalMessageInfo

func (m *QueryGetMappedAccountsResponse) GetAccount() []Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *QueryGetMappedAccountsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryParamsResponse")
	proto.RegisterType((*QueryShowAccountRequest)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryShowAccountRequest")
	proto.RegisterType((*QueryShowAccountResponse)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryShowAccountResponse")
	proto.RegisterType((*QueryListAccountRequest)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryListAccountRequest")
	proto.RegisterType((*QueryListAccountResponse)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryListAccountResponse")
	proto.RegisterType((*QueryGetShareKeysRequest)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryGetShareKeysRequest")
	proto.RegisterType((*QueryGetShareKeysResponse)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryGetShareKeysResponse")
	proto.RegisterType((*QueryGetSecretKeyRequest)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryGetSecretKeyRequest")
	proto.RegisterType((*QueryGetSecretKeyResponse)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryGetSecretKeyResponse")
	proto.RegisterType((*QueryGetMappedAccountsRequest)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryGetMappedAccountsRequest")
	proto.RegisterType((*QueryGetMappedAccountsResponse)(nil), "hackathonaccountrecovery.hackathonaccountrecovery.QueryGetMappedAccountsResponse")
}

func init() {
	proto.RegisterFile("hackathonaccountrecovery/hackathonaccountrecovery/query.proto", fileDescriptor_b3366ed22c2ad7f0)
}

var fileDescriptor_b3366ed22c2ad7f0 = []byte{
	// 814 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xcf, 0x6b, 0x13, 0x4f,
	0x14, 0xcf, 0x26, 0x6d, 0xbf, 0x64, 0xd2, 0xc3, 0xb7, 0x63, 0xc1, 0x1a, 0x6a, 0x2c, 0x73, 0xd0,
	0xd2, 0xc3, 0x0e, 0xad, 0xa7, 0x28, 0xb6, 0x34, 0x60, 0x83, 0xa6, 0xd2, 0x34, 0xf5, 0x20, 0x45,
	0x28, 0xd3, 0x38, 0x24, 0x4b, 0x9a, 0x9d, 0xed, 0xce, 0xb4, 0x35, 0x84, 0x1c, 0xac, 0xff, 0x80,
	0xa8, 0x7f, 0x84, 0x47, 0x0f, 0xde, 0x3d, 0x09, 0x3d, 0x16, 0xbc, 0x88, 0x07, 0x91, 0x56, 0xf0,
	0xe8, 0xd1, 0xab, 0x64, 0xf6, 0x6d, 0xb2, 0xf9, 0x85, 0x64, 0x93, 0x8b, 0x97, 0xb0, 0x79, 0x33,
	0xf3, 0x79, 0x9f, 0xcf, 0x67, 0xde, 0xbe, 0xb7, 0xe8, 0x5e, 0x99, 0x15, 0x2b, 0x4c, 0x95, 0x85,
	0xcd, 0x8a, 0x45, 0x71, 0x64, 0x2b, 0x97, 0x17, 0xc5, 0x31, 0x77, 0x6b, 0x74, 0xe0, 0xc2, 0xe1,
	0x11, 0x77, 0x6b, 0xa6, 0xe3, 0x0a, 0x25, 0xf0, 0xf2, 0xa0, 0x5d, 0xe6, 0xa0, 0x85, 0xe4, 0x0c,
	0xab, 0x5a, 0xb6, 0xa0, 0xfa, 0xd7, 0x43, 0x49, 0xce, 0x96, 0x44, 0x49, 0xe8, 0x47, 0xda, 0x7c,
	0x82, 0xe8, 0x7c, 0x49, 0x88, 0xd2, 0x01, 0xa7, 0xcc, 0xb1, 0x28, 0xb3, 0x6d, 0xa1, 0x98, 0xb2,
	0x84, 0x2d, 0x61, 0x75, 0xa9, 0x28, 0x64, 0x55, 0x48, 0xba, 0xcf, 0x24, 0xf7, 0x28, 0xd1, 0xe3,
	0xe5, 0x7d, 0xae, 0xd8, 0x32, 0x75, 0x58, 0xc9, 0xb2, 0xf5, 0x66, 0xd8, 0xbb, 0x3a, 0xbc, 0x48,
	0x87, 0xb9, 0xac, 0xea, 0xe7, 0x5a, 0x1b, 0xfe, 0x3c, 0xfc, 0x07, 0x80, 0xcc, 0xf0, 0x00, 0x92,
	0x17, 0x5d, 0xae, 0xf6, 0x2a, 0x1c, 0xac, 0x26, 0xb3, 0x08, 0x6f, 0x37, 0x65, 0xe6, 0x35, 0xb3,
	0x02, 0x3f, 0x3c, 0xe2, 0x52, 0x11, 0x89, 0xae, 0x74, 0x44, 0xa5, 0x23, 0x6c, 0xc9, 0xf1, 0x53,
	0x34, 0xe5, 0x29, 0x98, 0x33, 0x16, 0x8c, 0xc5, 0xc4, 0x4a, 0xda, 0x1c, 0xfa, 0xa2, 0x4c, 0x0f,
	0x32, 0x13, 0x3f, 0xfb, 0x76, 0x23, 0xf2, 0xee, 0xe7, 0xfb, 0x25, 0xa3, 0x00, 0x98, 0x84, 0xa2,
	0xab, 0x3a, 0xe9, 0x4e, 0x59, 0x9c, 0xac, 0x7b, 0xa7, 0x80, 0x0f, 0x9e, 0x45, 0x93, 0xe2, 0xc4,
	0xe6, 0xae, 0xce, 0x1b, 0x2f, 0x78, 0x7f, 0x88, 0x83, 0xe6, 0x7a, 0x0f, 0x00, 0xd5, 0xc7, 0xe8,
	0x3f, 0xc8, 0x0c, 0x5c, 0xef, 0x84, 0xe0, 0xea, 0x83, 0xfa, 0x50, 0x84, 0x01, 0xc5, 0x4d, 0x4b,
	0xaa, 0x2e, 0x8a, 0x1b, 0x08, 0xb5, 0x2b, 0x04, 0x72, 0xde, 0x34, 0xbd, 0x72, 0x32, 0x9b, 0xe5,
	0x64, 0x7a, 0x15, 0x0e, 0xe5, 0x64, 0xe6, 0x59, 0x89, 0xc3, 0xd9, 0x42, 0xe0, 0x24, 0xf9, 0x68,
	0x80, 0xaa, 0x8e, 0x1c, 0xa0, 0x6a, 0x37, 0xa8, 0x2a, 0x36, 0x9a, 0xaa, 0xcc, 0x44, 0xf3, 0x0a,
	0x5a, 0xda, 0x70, 0xb6, 0x43, 0x40, 0x54, 0x0b, 0xb8, 0xf5, 0x57, 0x01, 0x1e, 0xb1, 0x0e, 0x05,
	0x1f, 0x7c, 0x05, 0x59, 0xae, 0x76, 0xca, 0xcc, 0xe5, 0x39, 0x5e, 0xf3, 0x2b, 0x0b, 0xff, 0x8f,
	0x62, 0x15, 0x5e, 0x83, 0x7b, 0x6c, 0x3e, 0xe2, 0x05, 0x94, 0x50, 0x42, 0xb1, 0x03, 0xd9, 0xdc,
	0x2a, 0x75, 0xe2, 0x58, 0x21, 0x18, 0xc2, 0xf3, 0x28, 0x5e, 0xb5, 0x6c, 0x58, 0x8f, 0xe9, 0xf5,
	0x76, 0xa0, 0xcb, 0xf8, 0x89, 0xd0, 0xc6, 0xaf, 0xa1, 0x6b, 0x7d, 0x58, 0x83, 0xf1, 0x04, 0xc5,
	0xbd, 0x57, 0xc7, 0x23, 0x1f, 0x5b, 0x8c, 0x83, 0x7d, 0xed, 0x30, 0x59, 0x0d, 0xc8, 0xd6, 0xc1,
	0x1c, 0xaf, 0xf9, 0xb2, 0x09, 0x9a, 0x06, 0x9f, 0xb7, 0x02, 0x75, 0xdc, 0x11, 0x23, 0xe9, 0x00,
	0x81, 0xf6, 0x79, 0x20, 0x30, 0xef, 0x13, 0xc8, 0xb5, 0xdc, 0x6b, 0x07, 0xc8, 0x0b, 0x03, 0x5d,
	0xf7, 0xcf, 0x3e, 0x62, 0x8e, 0xc3, 0x9f, 0xc1, 0x25, 0xb7, 0x7c, 0x9f, 0xeb, 0x7c, 0x1f, 0xe2,
	0xed, 0x7b, 0xdf, 0xe8, 0x73, 0xef, 0x61, 0xfc, 0xfb, 0x64, 0xa0, 0xd4, 0x20, 0x0e, 0xff, 0x50,
	0xf9, 0xae, 0x9c, 0x4e, 0xa3, 0x49, 0xad, 0x03, 0x7f, 0x35, 0xd0, 0x94, 0xd7, 0xae, 0xf0, 0xfd,
	0x10, 0x44, 0x7b, 0xfb, 0x6a, 0x72, 0x63, 0x54, 0x18, 0x8f, 0x2f, 0x59, 0x3f, 0xfd, 0xfc, 0xe3,
	0x4d, 0xf4, 0x2e, 0x4e, 0xd3, 0xb0, 0x33, 0x08, 0xff, 0x36, 0x50, 0x22, 0xd0, 0x38, 0xf1, 0xc3,
	0xb0, 0xd4, 0x7a, 0xdb, 0x75, 0x32, 0x37, 0x16, 0x2c, 0xd0, 0xba, 0xa5, 0xb5, 0x3e, 0xc0, 0xd9,
	0x10, 0x5a, 0x65, 0x59, 0x9c, 0xec, 0x41, 0x90, 0xd6, 0xf5, 0xd4, 0x68, 0xe0, 0x5f, 0x06, 0x4a,
	0x04, 0x9a, 0x6b, 0x78, 0xe5, 0xbd, 0x53, 0x20, 0xbc, 0xf2, 0x3e, 0xdd, 0x9e, 0x64, 0xb5, 0xf2,
	0x75, 0xbc, 0x16, 0x42, 0xf9, 0x81, 0x25, 0x95, 0xaf, 0x1c, 0xbf, 0x8d, 0xa2, 0xe9, 0x60, 0x5b,
	0xc3, 0xa1, 0x69, 0xf6, 0x69, 0xe9, 0xc9, 0xcd, 0xf1, 0x80, 0x81, 0x68, 0x4b, 0x8b, 0x2e, 0x62,
	0x16, 0x42, 0x74, 0x89, 0xab, 0x3d, 0x3d, 0x15, 0x9a, 0x1f, 0x38, 0x92, 0xd6, 0x2b, 0xbc, 0xd6,
	0xa0, 0xf5, 0xc0, 0x28, 0x69, 0xd0, 0x7a, 0x6b, 0x70, 0x34, 0xf0, 0x4b, 0xb0, 0xc5, 0x6f, 0xa3,
	0xa3, 0xd9, 0xd2, 0xd5, 0xf2, 0x47, 0xb3, 0xa5, 0xbb, 0xff, 0x93, 0x27, 0xda, 0x96, 0x02, 0xce,
	0x87, 0xb5, 0xa5, 0xf5, 0xe1, 0x47, 0xeb, 0xc1, 0xa9, 0xd3, 0xc0, 0xaf, 0xa3, 0x68, 0xa6, 0xa7,
	0x65, 0xe3, 0xfc, 0x08, 0xec, 0xfb, 0x4e, 0xa0, 0xe4, 0xf6, 0x18, 0x11, 0xc7, 0x64, 0x4a, 0x55,
	0xc3, 0xfa, 0xaf, 0x89, 0x6c, 0x39, 0xd3, 0xc8, 0xec, 0x9c, 0x5d, 0xa4, 0x8c, 0xf3, 0x8b, 0x94,
	0xf1, 0xfd, 0x22, 0x65, 0xbc, 0xba, 0x4c, 0x45, 0xce, 0x2f, 0x53, 0x91, 0x2f, 0x97, 0xa9, 0xc8,
	0x6e, 0x7a, 0x20, 0xe2, 0xf3, 0xc1, 0xc9, 0x54, 0xcd, 0xe1, 0x72, 0x7f, 0x4a, 0x7f, 0x72, 0xdf,
	0xfe, 0x13, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x6e, 0x2b, 0x8e, 0x1e, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ShowAccount items.
	ShowAccount(ctx context.Context, in *QueryShowAccountRequest, opts ...grpc.CallOption) (*QueryShowAccountResponse, error)
	// Queries a list of ListAccount items.
	ListAccount(ctx context.Context, in *QueryListAccountRequest, opts ...grpc.CallOption) (*QueryListAccountResponse, error)
	// Queries a list of GetShareKeys items.
	GetShareKeys(ctx context.Context, in *QueryGetShareKeysRequest, opts ...grpc.CallOption) (*QueryGetShareKeysResponse, error)
	// Queries a list of GetSecretKey items.
	GetSecretKey(ctx context.Context, in *QueryGetSecretKeyRequest, opts ...grpc.CallOption) (*QueryGetSecretKeyResponse, error)
	// Queries a list of GetMappedAccounts items.
	GetMappedAccounts(ctx context.Context, in *QueryGetMappedAccountsRequest, opts ...grpc.CallOption) (*QueryGetMappedAccountsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/hackathonaccountrecovery.hackathonaccountrecovery.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShowAccount(ctx context.Context, in *QueryShowAccountRequest, opts ...grpc.CallOption) (*QueryShowAccountResponse, error) {
	out := new(QueryShowAccountResponse)
	err := c.cc.Invoke(ctx, "/hackathonaccountrecovery.hackathonaccountrecovery.Query/ShowAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListAccount(ctx context.Context, in *QueryListAccountRequest, opts ...grpc.CallOption) (*QueryListAccountResponse, error) {
	out := new(QueryListAccountResponse)
	err := c.cc.Invoke(ctx, "/hackathonaccountrecovery.hackathonaccountrecovery.Query/ListAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetShareKeys(ctx context.Context, in *QueryGetShareKeysRequest, opts ...grpc.CallOption) (*QueryGetShareKeysResponse, error) {
	out := new(QueryGetShareKeysResponse)
	err := c.cc.Invoke(ctx, "/hackathonaccountrecovery.hackathonaccountrecovery.Query/GetShareKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetSecretKey(ctx context.Context, in *QueryGetSecretKeyRequest, opts ...grpc.CallOption) (*QueryGetSecretKeyResponse, error) {
	out := new(QueryGetSecretKeyResponse)
	err := c.cc.Invoke(ctx, "/hackathonaccountrecovery.hackathonaccountrecovery.Query/GetSecretKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetMappedAccounts(ctx context.Context, in *QueryGetMappedAccountsRequest, opts ...grpc.CallOption) (*QueryGetMappedAccountsResponse, error) {
	out := new(QueryGetMappedAccountsResponse)
	err := c.cc.Invoke(ctx, "/hackathonaccountrecovery.hackathonaccountrecovery.Query/GetMappedAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ShowAccount items.
	ShowAccount(context.Context, *QueryShowAccountRequest) (*QueryShowAccountResponse, error)
	// Queries a list of ListAccount items.
	ListAccount(context.Context, *QueryListAccountRequest) (*QueryListAccountResponse, error)
	// Queries a list of GetShareKeys items.
	GetShareKeys(context.Context, *QueryGetShareKeysRequest) (*QueryGetShareKeysResponse, error)
	// Queries a list of GetSecretKey items.
	GetSecretKey(context.Context, *QueryGetSecretKeyRequest) (*QueryGetSecretKeyResponse, error)
	// Queries a list of GetMappedAccounts items.
	GetMappedAccounts(context.Context, *QueryGetMappedAccountsRequest) (*QueryGetMappedAccountsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ShowAccount(ctx context.Context, req *QueryShowAccountRequest) (*QueryShowAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowAccount not implemented")
}
func (*UnimplementedQueryServer) ListAccount(ctx context.Context, req *QueryListAccountRequest) (*QueryListAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccount not implemented")
}
func (*UnimplementedQueryServer) GetShareKeys(ctx context.Context, req *QueryGetShareKeysRequest) (*QueryGetShareKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShareKeys not implemented")
}
func (*UnimplementedQueryServer) GetSecretKey(ctx context.Context, req *QueryGetSecretKeyRequest) (*QueryGetSecretKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecretKey not implemented")
}
func (*UnimplementedQueryServer) GetMappedAccounts(ctx context.Context, req *QueryGetMappedAccountsRequest) (*QueryGetMappedAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMappedAccounts not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hackathonaccountrecovery.hackathonaccountrecovery.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShowAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShowAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hackathonaccountrecovery.hackathonaccountrecovery.Query/ShowAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShowAccount(ctx, req.(*QueryShowAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hackathonaccountrecovery.hackathonaccountrecovery.Query/ListAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListAccount(ctx, req.(*QueryListAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetShareKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetShareKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetShareKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hackathonaccountrecovery.hackathonaccountrecovery.Query/GetShareKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetShareKeys(ctx, req.(*QueryGetShareKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetSecretKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSecretKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSecretKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hackathonaccountrecovery.hackathonaccountrecovery.Query/GetSecretKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSecretKey(ctx, req.(*QueryGetSecretKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetMappedAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMappedAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetMappedAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hackathonaccountrecovery.hackathonaccountrecovery.Query/GetMappedAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetMappedAccounts(ctx, req.(*QueryGetMappedAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hackathonaccountrecovery.hackathonaccountrecovery.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ShowAccount",
			Handler:    _Query_ShowAccount_Handler,
		},
		{
			MethodName: "ListAccount",
			Handler:    _Query_ListAccount_Handler,
		},
		{
			MethodName: "GetShareKeys",
			Handler:    _Query_GetShareKeys_Handler,
		},
		{
			MethodName: "GetSecretKey",
			Handler:    _Query_GetSecretKey_Handler,
		},
		{
			MethodName: "GetMappedAccounts",
			Handler:    _Query_GetMappedAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hackathonaccountrecovery/hackathonaccountrecovery/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryShowAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Account != nil {
		{
			size, err := m.Account.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		for iNdEx := len(m.Account) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Account[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetShareKeysRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetShareKeysRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetShareKeysRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Minshares != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Minshares))
		i--
		dAtA[i] = 0x18
	}
	if m.Totalshares != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Totalshares))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetShareKeysResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetShareKeysResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetShareKeysResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Secretkey) > 0 {
		for iNdEx := len(m.Secretkey) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Secretkey[iNdEx])
			copy(dAtA[i:], m.Secretkey[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Secretkey[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSecretKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSecretKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSecretKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccountOwner) > 0 {
		i -= len(m.AccountOwner)
		copy(dAtA[i:], m.AccountOwner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AccountOwner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSecretKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSecretKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSecretKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SecretKey) > 0 {
		i -= len(m.SecretKey)
		copy(dAtA[i:], m.SecretKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SecretKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMappedAccountsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMappedAccountsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMappedAccountsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMappedAccountsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMappedAccountsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMappedAccountsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		for iNdEx := len(m.Account) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Account[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryShowAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Account != nil {
		l = m.Account.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Account) > 0 {
		for _, e := range m.Account {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetShareKeysRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Totalshares != 0 {
		n += 1 + sovQuery(uint64(m.Totalshares))
	}
	if m.Minshares != 0 {
		n += 1 + sovQuery(uint64(m.Minshares))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetShareKeysResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Secretkey) > 0 {
		for _, s := range m.Secretkey {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetSecretKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccountOwner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSecretKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SecretKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMappedAccountsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMappedAccountsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Account) > 0 {
		for _, e := range m.Account {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Account == nil {
				m.Account = &Account{}
			}
			if err := m.Account.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = append(m.Account, Account{})
			if err := m.Account[len(m.Account)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetShareKeysRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetShareKeysRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetShareKeysRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Totalshares", wireType)
			}
			m.Totalshares = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Totalshares |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Minshares", wireType)
			}
			m.Minshares = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Minshares |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetShareKeysResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetShareKeysResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetShareKeysResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Secretkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Secretkey = append(m.Secretkey, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSecretKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSecretKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSecretKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSecretKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSecretKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSecretKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMappedAccountsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMappedAccountsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMappedAccountsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMappedAccountsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMappedAccountsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMappedAccountsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = append(m.Account, Account{})
			if err := m.Account[len(m.Account)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
